version: '3'

services:
  hugo:
    container_name: hugo
    hostname: hugo
    build:
      context: ./dockerfile
      dockerfile: Dockerfile_hugo
    image: ssg/hugo:0.82.1
    volumes:
        - "./content:/src"
    entrypoint: bash
    environment:
      - TZ=Asia/Tokyo
    ports:
        - "10092:1313"
    tty: true
    working_dir: /src
    restart: unless-stopped
