FROM klakegg/hugo:0.82.1-ext-ubuntu

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    tzdata && \
    apt-get clean && \
    npm install autoprefixer && \
    npm install postcss-cli
